services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    env_file: .env.app
    volumes:
      - ./app:/app
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://app:3000
    env_file: .env.cloudflare
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge